Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Invalid OTP entered.
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
Invalid OTP entered.
Watching for file changes with StatReloader
Internal Server Error: /forgot-password-otp/
Traceback (most recent call last):
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\BidBazaar\commerce\auctions\views.py", line 152, in password_otp
    if int(user_otp) == request.session.get('otp', 0):
       ^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /forgot-password-otp/
Traceback (most recent call last):
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\BidBazaar\commerce\auctions\views.py", line 153, in password_otp
    if int(user_otp) == request.session.get('otp', 0):
       ^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\commerce\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /forgot-password/
Traceback (most recent call last):
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\BidBazaar\commerce\auctions\views.py", line 122, in forgot_password
    user = User.objects.get(username=username, email=email)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
auctions.models.User.DoesNotExist: User matching query does not exist.
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /forgot-password-otp/
Traceback (most recent call last):
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\BidBazaar\commerce\auctions\views.py", line 191, in password_otp
    return redirect('otp_success', message="Password sent to mail successfully")  # Redirect to the success page
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'otp_success' with keyword arguments '{'message': 'Password sent to mail successfully'}' not found. 1 pattern(s) tried: ['otp\\-success/\\Z']
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /bidbazaar-logo.png
Not Found: /bidbazaar-logo.png
Not Found: /bidbazaar-logo.png
Not Found: /bidbazaar-logo.png
Not Found: /bidbazaar-logo.png
Bids for listing 13: <QuerySet []>
No bids found for listing 13
Bids for listing 10: <QuerySet []>
No bids found for listing 10
Bids for listing 9: <QuerySet [<Bid: Bid object (15)>]>
Highest bidder for listing 9: blockbusterandy
D:\Projects\BidBazaar\commerce\commerce\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\commerce\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\commerce\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\commerce\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\commerce\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\commerce\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\commerce\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\commerce\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\commerce\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\commerce\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\commerce\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\commerce\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\commerce\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\commerce\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\commerce\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\commerce\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\commerce\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\commerce\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\commerce\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\commerce\settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /category/
Traceback (most recent call last):
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\BidBazaar\commerce\auctions\views.py", line 338, in categories
    return render(request, "auctions/categories.html", {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 12: 'endif', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
Bids for listing 14: <QuerySet []>
No bids found for listing 14
Bids for listing 11: <QuerySet []>
No bids found for listing 11
Not Found: /favicon.ico
Bids for listing 8: <QuerySet []>
No bids found for listing 8
Bids for listing 14: <QuerySet []>
No bids found for listing 14
Not Found: /favicon.ico
Bids for listing 12: <QuerySet [<Bid: Bid object (13)>, <Bid: Bid object (14)>]>
Highest bidder for listing 12: blockbusterandy
Watching for file changes with StatReloader
Internal Server Error: /profile/
Traceback (most recent call last):
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\BidBazaar\commerce\auctions\views.py", line 353, in view_profile
    return render(request, "auctions/profile/view_profile.html", {'user': user})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'edit_profile' not found. 'edit_profile' is not a valid view function or pattern name.
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /profile/
Traceback (most recent call last):
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\BidBazaar\commerce\auctions\views.py", line 353, in view_profile
    return render(request, "auctions/profile/view_profile.html", {'user': user})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'edit_password' not found. 'edit_password' is not a valid view function or pattern name.
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /profile/
Traceback (most recent call last):
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\BidBazaar\commerce\auctions\views.py", line 353, in view_profile
    return render(request, "auctions/profile/view_profile.html", {'user': user})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'edit_password' not found. 'edit_password' is not a valid view function or pattern name.
D:\Projects\BidBazaar\commerce\auctions\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\models.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\models.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /profile/edit/
Traceback (most recent call last):
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
            ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\BidBazaar\commerce\auctions\views.py", line 359, in edit_profile
    user.username = request.POST['username']
                    ~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'username'
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\models.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\models.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\models.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /profile/edit/password/
Traceback (most recent call last):
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
            ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'original_password'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\BidBazaar\commerce\auctions\views.py", line 377, in edit_password
    original_password = request.POST['original_password']
                        ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'original_password'
Not Found: /accounts/login/
D:\Projects\BidBazaar\commerce\auctions\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
D:\Projects\BidBazaar\commerce\auctions\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /accounts/login/
D:\Projects\BidBazaar\commerce\auctions\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
D:\Projects\BidBazaar\commerce\commerce\settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aniket\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
D:\Projects\BidBazaar\commerce\commerce\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\auctions\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /accounts/login/
D:\Projects\BidBazaar\commerce\auctions\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Bids for listing 11: <QuerySet []>
No bids found for listing 11
Bids for listing 11: <QuerySet [<Bid: Bid object (16)>]>
Highest bidder for listing 11: jadhavaniket19
Bids for listing 11: <QuerySet [<Bid: Bid object (16)>]>
Highest bidder for listing 11: jadhavaniket19
Bids for listing 11: <QuerySet [<Bid: Bid object (16)>]>
Highest bidder for listing 11: jadhavaniket19
Bids for listing 11: <QuerySet [<Bid: Bid object (16)>]>
Highest bidder for listing 11: jadhavaniket19
Bids for listing 14: <QuerySet []>
No bids found for listing 14
Bids for listing 14: <QuerySet []>
No bids found for listing 14
Bids for listing 13: <QuerySet []>
No bids found for listing 13
Not Found: /media/
Not Found: /media/
Bids for listing 15: <QuerySet []>
No bids found for listing 15
Not Found: /media/
Watching for file changes with StatReloader
D:\Projects\BidBazaar\commerce\commerce\settings.py changed, reloading.
